Repository w3c-ccg/did-spec, pull requests merged in 2019-08, with the labels that each got.

#232 Remove NPM packaging support.
  CHANGELOG.md
  js/index.js
  package.json
Labels: markup/infra

#242 Add `controller` pattern example (also replaces Guardianship).
  index.html
Labels: editorial, merge

#239 moved list from charter to spec
  index.html
Labels: intro/overview, merge, non-normative

#208 Add link to spec for discovering DIDs from DNS.
  common.js
  index.html
Labels: merge, non-normative

#206 Added 'id' attribute of the 'service' definition for DID doc example
  index.html
Labels: editorial, merge

#210 Remove untestable requirements.
  index.html
Labels: clarify, merge

#196 Add "hl" DID URL matrix parameter.
  common.js
  index.html
Labels: discuss, merge

#194 Add "version-id" and "version-time" DID URL matrix parameters.
  index.html
Labels: discuss, merge

#179 Update abstract to build bigger tent / weaken "decentralization" requirement
  index.html
Labels: intro/overview, merge, non-normative

#234 added section on interop
  index.html
Labels: intro/overview, non-normative

#246 Replace draft context URI with w3.org one in all examples
  index.html
Labels: editorial

#249 Fix references in "Proof" section.
  index.html
Labels: editorial

#250 Change "Decentralized Identifier Registry" to "DID Registry".
  index.html
  terms.html
Labels: editorial

#251 (editorial) punctuation and whitespace tidy-up
  index.html
Labels: editorial, markup/infra

#254 Clarify intent in section on persistence
  index.html
Labels: clarify

#255 Fix inconsistent use of term 'DID subject'
  index.html
Labels: clarify

#253 clarify second MUST in 4.7 Fragment
  index.html
Labels: clarify, merge

#258 Reference DID Resolution spec.
  common.js
  index.html
Labels: editorial

#259 Add magic css so comments in examples aren't selected
  index.html
Labels: editorial, markup/infra, merge

#260 Editorial updates to intro mostly
  index.html
Labels: editorial, intro/overview, merge

#261 Correct description of DID Subject and add dfn
  index.html
  terms.html
Labels: clarify, merge

#257 Add basic info to the data model section
  index.html
Labels: editorial, intro/overview, merge

#262 Attempt dfn of DID Controller
  index.html
  terms.html
Labels: clarify
